[[redirects]]
  from = "/portfolio/*"
  to = "https://emmanuel-portfolio-image-bucket.s3.us-west-2.amazonaws.com/portfolio/:splat"
  host = "emmanuel-portfolio-image-bucket.s3.us-west-2.amazonaws.com"
  force = true
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200