[redirects]
  from = "/portfolio/*"
  to = "https://emmanuel-portfolio-image-bucket.s3.us-west-2.amazonaws.com/:splat"
  host = "emmanuel-portfolio-image-bucket.s3.us-west-2.amazonaws.com"
  force = true
  status = 200

  from = "/*"
  to = "/index.html"
  status = 200