version: '3'

services:
  dev_server:
    container_name: dev_server
    build: ../../server
    environment:
      - WIREGUARD_DB=Host=dev_wireguard_db;Database=postgres;Username=postgres;Password=password
      - APPLICATION_CONTEXT=Host=dev_db;Database=postgres;Username=postgres;Password=password
    depends_on:
      - dev_db

  dev_client:
    container_name: dev_client
    build:
      dockerfile: ../ops/development/devClient.Dockerfile
      context: ../../client
    ports:
      - 80:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ../../client:/usr/src/app
    depends_on:
      - dev_server

  dev_db:
    container_name: dev_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  dev_wireguard_db:
    container_name: dev_wireguard_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ../../../wireguard/sql/admindb.sql:/docker-entrypoint-initdb.d/admindb.sql