version: '3'

services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=emmanueltorreshn.com
      - VALIDATION=http
      - STAGING=false
      - SUBDOMAINS=www,admin
    volumes:
      - /swag:/config
      - ./ops/deploying/default.conf:/config/nginx/site-confs/default
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  server:
    container_name: portfolio_server
    build: ./src/portfolio/server
    env_file:
      - './src/portfolio/server/.env'
    depends_on:
      - portfolio_db

  client:
    container_name: portfolio_client
    build:
      dockerfile: ../../../ops/deploying/client.Dockerfile
      context: ./src/portfolio/client
    volumes:
      - ./src/portfolio/client/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
  portfolio_db:
    image: postgres
    container_name: portfolio_db
    restart: always
    env_file:
      - './src/portfolio/sql/portfoliodb.env'