version: '3'

services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=emmanueltorreshn.com
      - VALIDATION=http
      - STAGING=false
      - SUBDOMAINS=www,admin
    volumes:
      - /swag:/config
      - ./src/ops/deploying/default.conf:/config/nginx/site-confs/default
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  server:
    container_name: portfolio_server
    build: ./src/server
    depends_on:
      - db

  client:
    container_name: portfolio_client
    build:
      dockerfile: ../ops/deploying/client.Dockerfile
      context: ./src/client
    volumes:
      - ./src/client/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server

  wireguard_client: 
    container_name: wireguard_client
    build:
      dockerfile: ../../src/ops/deploying/client.Dockerfile
      context: ./wireguard/client
    volumes:
      - ./wireguard/client/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wireguard_db
    extra_hosts:
      - host.docker.internal:host-gateway

  db:
    image: postgres
    container_name: portfolio_db
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  wireguard_db:
    image: postgres
    container_name: wireguard_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./wireguard/sql/admindb.sql:/docker-entrypoint-initdb.d/admindb.sql