version: "3"

services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - VALIDATION=http
    env_file:
      - swag.env
    volumes:
      - /swag:/config
      - ./default.conf:/config/nginx/site-confs/default
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  db:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - db.env


  app:
    container_name: app
    build:
      dockerfile: ../Dockerfile
      context: ./src
    env_file:
      - app.env
    depends_on:
      db:
        condition: service_started
