version: '3'

services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=emmanueltorreshn.com
      - VALIDATION=http
      - STAGING=false
      - SUBDOMAINS=www,
    volumes:
      - /swag:/config
      - ./src/ops/deploying/default.conf:/config/nginx/site-confs/default
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  server:
    build: 
      dockerfile: ../ops/deploying/server.Dockerfile
      context: ./src/server
    ports:
      - 5000:3000
    env_file:
      - ./src/server/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  client:
    build:
      dockerfile: ../ops/deploying/client.Dockerfile
      context: ./src/client
    volumes:
      - ./src/client/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./src/sql/createdb.sql:/docker-entrypoint-initdb.d/createdb.sql
      - ./src/sql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

  wireguard_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./src/sql/admindb.sql:/docker-entrypoint-initdb.d/admindb.sql