version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./sql/createdb.sql:/docker-entrypoint-initdb.d/createdb.sql
      - ./sql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

  server:
    build: ./server
    ports:
      - 5000:3000
    env_file:
      - ./server/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db