version: '3'

services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${{ vars.ENV_APP_TIMEZONE }}
      - URL=${{ vars.ENV_APP_URL }}
      - VALIDATION=http
      - STAGING=${{ vars.ENV_IS_STAGING }}
      - SUBDOMAINS=${{ vars.ENV_APP_SUBDOMAINS }}
    volumes:
      - /swag:/config
      - ./default.conf:/config/nginx/site-confs/default
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${{ vars.ENV_DB_PASSWORD }}
      - POSTGRES_USER=${{ vars.ENV_DB_USER }}
      - POSTGRES_DB=${{ vars.ENV_DB_NAME }}

  app:
    container_name: app
    build:
      dockerfile: ../Dockerfile
      context: ./src
    environment:
      - APPLICATION_CONTEXT=Host=db;Database=${{ vars.ENV_DB_NAME }};Username=${{ vars.ENV_DB_USER }};Password=${{ vars.ENV_DB_PASSWORD }}
    depends_on:
      db:
        condition: service_started
