version: '3'

services:
  server:
    build: 
      dockerfile: ../ops/deploying/server.Dockerfile
      context: ./server
    ports:
      - 5000:3000
    env_file:
      - ./server/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  client:
    build:
      dockerfile: ../ops/deploying/client.Dockerfile
      context: ./client
    ports:
      - 80:80
    volumes:
      - ./client/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./sql/createdb.sql:/docker-entrypoint-initdb.d/createdb.sql
      - ./sql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql