version: '3'

services:
  dev_db:
    container_name: dev_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  dev_app:
    container_name: dev_app
    build:
      dockerfile: ../Dockerfile
      context: ./src
    ports:
      - 80:5000
    environment:
      - APPLICATION_CONTEXT=Host=dev_db;Database=postgres;Username=postgres;Password=password
    depends_on:
      dev_db:
        condition: service_started