name: "backup"

on:
  schedule:
    - cron: "0 0 * * 6"

jobs:
  backup:
    runs-on: ["self-hosted", "portfolio-vm"]
    steps:
      - name: create backup
        run: |
          docker exec wireguard_db pg_dump -U wg_admin -F t postgres > /home/github/dumps/postgres-$(date +%Y-%m-%d).sql

  retrieve:
    runs-on: ["self-hosted", "backup-vm"]
    needs: [backup]
    steps:
      - name: retrieve backup
        run: |
          sudo wg-quick up emmanuelvpn
          scp 'root@10.200.10.69:/home/github/dumps/postgres*' /home/emmanuel/dumps
          sudo wg-quick down emmanuelvpn

  remove:
    runs-on: ["self-hosted", "portfolio-vm"]
    needs: [retrieve]
    steps:
      - name: delete backups
        run: |
          cd /home/github/dumps
          rm postgres*
