name: "integrate"

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ["self-hosted", "portfolio-vm"]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.4.0

      - name: test
        run: |
          cd src/ops/testing
          docker-compose up -d --build
          docker-compose exec -T client_test npm run ops:test

  teardown:
    runs-on: self-hosted
    if: ${{ always() }}
    needs: [run-tests]
    steps:
      - name: teardown
        run: |
          cd src/ops/testing
          docker-compose down